config/urls.py
# Django
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import include, path, re_path
from django.views import defaults as default_views
from django.views.generic import TemplateView

# Third Party
from allauth.account.decorators import secure_admin_login
from rest_framework_nested import routers
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

# Squarelet
from squarelet.core.views import HomeView, SelectPlanView
from squarelet.oidc.views import OIDCRedirectURIUpdater, token_view
from squarelet.organizations.fe_api.viewsets import (
    InvitationViewSet as FEInvitationViewSet,
    OrganizationViewSet as FEOrganizationViewSet,
)
from squarelet.organizations.viewsets import ChargeViewSet, OrganizationViewSet
from squarelet.payments.views import PlanDetailView, PlanRedirectView
from squarelet.users.fe_api.viewsets import UserViewSet as FEUserViewSet
from squarelet.users.views import (
    LoginView,
    SignupView,
    UserConnectionsView,
    UserEmailView,
    UserOnboardingView,
)
from squarelet.users.viewsets import (
    RefreshTokenViewSet,
    UrlAuthTokenViewSet,
    UserViewSet,
)

admin.autodiscover()
admin.site.login = secure_admin_login(admin.site.login)

router = routers.DefaultRouter()
router.register("users", UserViewSet)
router.register("url_auth_tokens", UrlAuthTokenViewSet, basename="url_auth_token")
router.register("refresh_tokens", RefreshTokenViewSet, basename="refresh_token")
router.register("organizations", OrganizationViewSet)
router.register("charges", ChargeViewSet)


fe_api_router = routers.DefaultRouter()
fe_api_router.register(
    r"organizations", FEOrganizationViewSet, basename="fe-organizations"
)
fe_api_router.register(r"invitations", FEInvitationViewSet, basename="fe-invitations")
fe_api_router.register(r"users", FEUserViewSet, basename="fe-users")


def redirect_erh(request, path=""):
    return redirect(
        "https://www.muckrock.com/project/elections-2024-1169/", permanent=True
    )


urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("plans/<int:pk>-<slug:slug>/", PlanDetailView.as_view(), name="plan_detail"),
    path("plans/<int:pk>/", PlanRedirectView.as_view(), name="plan_detail_id"),
    path("plans/<slug:slug>/", PlanRedirectView.as_view(), name="plan_detail_slug"),
    path("selectplan/", SelectPlanView.as_view(), name="select_plan"),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("squarelet.users.urls", namespace="users")),
    path(
        "organizations/",
        include("squarelet.organizations.urls", namespace="organizations"),
    ),
    path("glomar/", include("squarelet.glomar.urls", namespace="glomar")),
    # override the allauth views with our version
    re_path("accounts/$", UserConnectionsView.as_view(), name="account_connections"),
    re_path("accounts/email/$", UserEmailView.as_view(), name="account_email"),
    re_path("accounts/login/$", LoginView.as_view(), name="account_login"),
    re_path(
        "accounts/onboard/$", UserOnboardingView.as_view(), name="account_onboarding"
    ),
    path("accounts/signup/", SignupView.as_view(), name="account_signup"),
    # Custom MFA URLs that override allauth defaults
    path("accounts/2fa/", include("squarelet.mfa.urls")),
    path("accounts/", include("allauth.urls")),
    path("accounts/", include("allauth.socialaccount.urls")),
    path("api/", include(router.urls)),
    path("fe_api/", include((fe_api_router.urls, "fe_api"), namespace="fe_api")),
    path("api/token/", TokenObtainPairView.as_view(), name="token_obtain_pair"),
    path("api/refresh/", TokenRefreshView.as_view(), name="token_refresh"),
    path("openid/", include("oidc_provider.urls", namespace="oidc_provider")),
    path("openid/jwt", token_view, name="oidc_jwt"),
    path("hijack/", include("hijack.urls", namespace="hijack")),
    re_path(r"^robots\.txt", include("robots.urls")),
    re_path(
        r"^election-hub/(?P<path>.*)?$",
        redirect_erh,
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]

# Conditionally add the API endpoint based on the environment
if settings.ENV == "staging" or settings.ENV == "dev":
    urlpatterns.append(
        path(
            "api/clients/<int:client_id>/redirect_uris/",
            OIDCRedirectURIUpdater.as_view(),
            name="oidc_redirect_uri_updater",
        )
    )

if "debug_toolbar" in settings.INSTALLED_APPS:
    # Third Party
    import debug_toolbar

    urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

squarelet/glomar/urls.py
# Django
from django.urls import path

from . import views

app_name = "glomar"

urlpatterns = [
    path("", views.GlomarDashboardView.as_view(), name="dashboard"),
    path(
        "users/<slug:username>/",
        views.GlomarUserDetailView.as_view(),
        name="user_detail",
    ),
    path(
        "organizations/<slug:slug>/",
        views.GlomarOrganizationDetailView.as_view(),
        name="organization_detail",
    ),
]

squarelet/mfa/urls.py
"""Custom MFA URL configuration to use views that redirect to user detail page."""

# Django
from django.urls import path

# Local
from . import views

app_name = "mfa"

urlpatterns = [
    # TOTP URLs
    path("totp/activate/", views.activate_totp, name="mfa_activate_totp"),
    path("totp/deactivate/", views.deactivate_totp, name="mfa_deactivate_totp"),
    # Recovery codes URLs
    path(
        "recovery-codes/generate/",
        views.generate_recovery_codes,
        name="mfa_generate_recovery_codes",
    ),
    # WebAuthn URLs
    path("webauthn/add/", views.add_webauthn, name="mfa_add_webauthn"),
    path(
        "webauthn/<int:pk>/remove/",
        views.remove_webauthn,
        name="mfa_remove_webauthn",
    ),
    path(
        "webauthn/<int:pk>/edit/",
        views.edit_webauthn,
        name="mfa_edit_webauthn",
    ),
]

squarelet/users/urls.py
# Django
from django.urls import path

# Local
from . import views

app_name = "users"
urlpatterns = [
    # path("", view=views.UserListView.as_view(), name="list"),
    path("~mailgun/", view=views.mailgun_webhook, name="mailgun"),
    # Redirect tilde routes to current user routes
    path(
        "~redirect/",
        view=views.UserRedirectView.as_view(),
        kwargs={"target_view": "detail"},
        name="redirect",
    ),
    path(
        "~update/",
        view=views.UserRedirectView.as_view(),
        kwargs={"target_view": "update"},
        name="update_redirect",
    ),
    path(
        "~payment/",
        view=views.UserRedirectView.as_view(),
        kwargs={"target_view": "payment"},
        name="payment_redirect",
    ),
    path(
        "~receipts/",
        view=views.UserRedirectView.as_view(),
        kwargs={"target_view": "receipts"},
        name="receipts_redirect",
    ),
    # Private username-based routes with staff access
    path("<str:username>/", view=views.UserDetailView.as_view(), name="detail"),
    path("<str:username>/update/", view=views.UserUpdateView.as_view(), name="update"),
    path(
        "<str:username>/payment/", view=views.UserPaymentView.as_view(), name="payment"
    ),
    path("<str:username>/receipts/", view=views.Receipts.as_view(), name="receipts"),
    path(
        "<str:username>/invitations/",
        view=views.UserInvitationsView.as_view(),
        name="invitations",
    ),
    path(
        "<str:username>/requests/",
        view=views.UserRequestsView.as_view(),
        name="requests",
    ),
]

squarelet/core/models.py
"""Misc database utilities"""

# Django
from django.db.models import Func
from django.db.models.expressions import Value


class Interval(Func):
    """PostgreSQL interval type"""

    # pylint: disable=abstract-method

    template = "interval %(expressions)s"

    def __init__(self, expression, **extra):
        super().__init__(Value(expression), **extra)

squarelet/elections/models.py
# Django
from django.db import models
from django.utils.translation import gettext_lazy as _

# Squarelet
from squarelet.core.fields import AutoCreatedField, AutoLastModifiedField
from squarelet.elections.choices import Category


class ElectionResource(models.Model):
    """An election resource available to journalists"""

    name = models.CharField(
        _("name"),
        help_text=_("The name of the resource"),
    )
    source = models.CharField(
        _("source"),
        help_text=_("Who contributed the resource"),
    )
    category = models.IntegerField(
        _("category"),
        choices=Category.choices,
        help_text=("The category of the resource"),
    )
    description = models.TextField(
        _("description"),
        help_text=_("A brief description of the resource"),
    )
    url = models.URLField(
        _("url"),
        help_text=_("The URL where the resource can be accessed"),
    )
    active = models.BooleanField(
        _("active"),
        default=True,
        help_text=_("Should this resource be shown"),
    )

    subtypes = models.ManyToManyField(
        verbose_name=_("subtypes"),
        to="organizations.OrganizationSubtype",
        related_name="resources",
        help_text=_("The organization subtypes which may access this resource"),
        blank=True,
    )
    members = models.ManyToManyField(
        verbose_name=_("members"),
        to="organizations.Organization",
        related_name="resources",
        help_text=_(
            "Organizations which are a member of this organization "
            "may access this resource"
        ),
        limit_choices_to={"individual": False},
        blank=True,
    )

    created_at = AutoCreatedField(
        _("created at"),
        help_text=_("When this resource was created"),
    )
    updated_at = AutoLastModifiedField(
        _("updated at"),
        help_text=_("When this resource was last updated"),
    )

    def __str__(self):
        return self.name

squarelet/hijacks/models.py
# hijacks/models.py
# Django
from django.db import models

# Squarelet
from squarelet.users.models import User


class HijackLog(models.Model):
    hijacker = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="hijacker_logs"
    )
    hijacked = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="hijacked_logs"
    )
    action = models.CharField(
        max_length=10, choices=[("start", "Started"), ("end", "Ended")]
    )
    timestamp = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-timestamp"]

    def __str__(self):
        return f"{self.hijacker} → {self.hijacked} ({self.action})"

squarelet/core/forms.py
# Django
from django import forms
from django.conf import settings
from django.forms.widgets import ClearableFileInput
from django.utils.translation import gettext_lazy as _


class StripeForm(forms.Form):
    """Base class for forms which include stripe fields"""

    stripe_pk = forms.CharField(
        widget=forms.HiddenInput(),
        initial=settings.STRIPE_PUB_KEY,
    )
    stripe_token = forms.CharField(widget=forms.HiddenInput(), required=False)
    use_card_on_file = forms.TypedChoiceField(
        label=_("Use Credit Card on File"),
        coerce=lambda x: x == "True",
        initial=True,
        widget=forms.RadioSelect,
    )
    remove_card_on_file = forms.BooleanField(initial=False, required=False)

    def __init__(self, *args, **kwargs):
        self.organization = kwargs.pop("instance", None)
        super().__init__(*args, **kwargs)
        self._set_card_options()

    def _set_card_options(self):
        card = None
        if self.organization:
            customer = self.organization.customer()
            card = customer.card
        if card:
            self.fields["use_card_on_file"].choices = (
                (True, customer.card_display),
                (False, _("New Card")),
            )
            self.fields["remove_card_on_file"].label = customer.card_display
        else:
            del self.fields["use_card_on_file"]
            del self.fields["remove_card_on_file"]
            self.fields["stripe_token"].required = True

    def clean(self):
        data = super().clean()
        if data.get("use_card_on_file") and data.get("stripe_token"):
            self.add_error(
                "use_card_on_file",
                _("You cannot use your card on file and enter a credit card number."),
            )
        return data


class AvatarWidget(ClearableFileInput):
    template_name = "widgets/avatar.html"
    clear_checkbox_label = _("Clear")
    input_text = _("Replace")
    initial_text = _("Current")

    def get_context(self, name, value, attrs):
        ctx = super().get_context(name, value, attrs)
        # Add flags / labels for empty state
        has_file = bool(value and getattr(value, "url", None))
        ctx["widget"]["has_file"] = has_file
        ctx["widget"]["upload_label"] = _("Replace") if has_file else _("Upload")
        ctx["widget"]["help_text"] = attrs.get("help_text") or ctx.get("help_text")
        return ctx

squarelet/core/views.py
# Django
from django.urls import reverse
from django.views.generic.base import RedirectView, TemplateView

# Squarelet
from squarelet.organizations.models import Plan


class HomeView(RedirectView):
    permanent = False

    def get_redirect_url(self, *args, **kwargs):
        if self.request.user.is_authenticated:
            return reverse(
                "users:detail", kwargs={"username": self.request.user.username}
            )
        else:
            return reverse("select_plan")


class SelectPlanView(TemplateView):
    template_name = "pages/selectplan.html"

    def get_context_data(self, **kwargs):
        # pylint: disable=too-many-locals
        context = super().get_context_data(**kwargs)
        user = self.request.user
        pro_plan = None
        org_plans = None
        if not user.is_anonymous:
            pro_plan = user.individual_organization.subscription
            org_plans = user.organizations.filter(
                subscriptions__isnull=False,
                individual=False,
            ).distinct()
        context["user"] = user
        context["pro_plan"] = pro_plan
        context["org_plans"] = org_plans

        # Add Sunlight plans structured by tier and payment schedule
        sunlight_plans_list = Plan.objects.filter(
            slug__startswith="sunlight-", wix=True
        ).order_by("slug")

        # Structure the plans as: tiers -> each tier has monthly and annual plans
        sunlight_tiers = {}
        for plan in sunlight_plans_list:
            # Extract tier from slug: "sunlight-essential", "sunlight-essential-annual"
            if plan.slug.endswith("-annual"):
                tier_name = plan.slug.replace("sunlight-", "").replace("-annual", "")
                payment_type = "annual"
            else:
                tier_name = plan.slug.replace("sunlight-", "")
                payment_type = "monthly"

            if tier_name not in sunlight_tiers:
                sunlight_tiers[tier_name] = {
                    "name": tier_name.title(),
                    "short_description": plan.short_description,
                    "monthly": None,
                    "annual": None,
                }

            sunlight_tiers[tier_name][payment_type] = plan

        # Fetch nonprofit variant plans and add them to tiers
        for tier_name, tier_data in sunlight_tiers.items():
            for payment_type in ["monthly", "annual"]:
                if tier_data[payment_type]:
                    standard_plan = tier_data[payment_type]
                    nonprofit_slug = standard_plan.nonprofit_variant_slug
                    if nonprofit_slug:
                        try:
                            nonprofit_plan = Plan.objects.get(slug=nonprofit_slug)
                            tier_data[payment_type] = {
                                "standard": standard_plan,
                                "nonprofit": nonprofit_plan,
                            }
                        except Plan.DoesNotExist:
                            # No nonprofit variant exists, keep the standard plan
                            tier_data[payment_type] = {
                                "standard": standard_plan,
                                "nonprofit": None,
                            }

        # Convert to ordered list for template
        tier_order = ["essential", "enhanced", "enterprise"]
        context["sunlight_tiers"] = [
            sunlight_tiers[tier] for tier in tier_order if tier in sunlight_tiers
        ]

        return context

squarelet/templates/payments/plan.html
{% extends "account/base.html" %}

{% load i18n static django_vite %}
{% load handleintent pass_query %}
{% load markdown %}
{% load humanize %}

{% block head_title %}{% trans "Select plan" %}{% endblock %}

{% block vite %}
{{ block.super }}
{% vite_asset "frontend/views/plan.ts" %}
{% endblock %}

{% block content %}
<div class="container">
  <div class="plan premium">
    <header>
      <h2 class="header-display">
        <span class="heavy-underline premium">{{ plan.name }}</span>
      </h2>
    </header>

    <main>
      <div class="plan-actions">
        <!-- Show existing subscriptions for authenticated users -->
        {% if user.is_authenticated and existing_subscriptions %}
          <div class="existing-subscriptions">
            <h3>{% trans "Active Subscriptions" %}</h3>
            <ul>
            {% for subscription, org in existing_subscriptions %}
              <li class="subscription-info">
                <a href="{% url "organizations:detail" org.slug %}">{{ org.name }}</a> is already subscribed to {{ plan.name }}
              </li>
            {% endfor %}
            </ul>
          </div>
        {% endif %}

        {% if user.is_authenticated and show_waitlist %}
        <!-- Waitlist Form -->
        <div class="waitlist card">
          <div class="waitlist">
            <h3>{% trans "Subscription Limit Reached" %}</h3>
            <p>{% trans "This plan is currently at capacity. Join the waitlist to be notified when a spot becomes available." %}</p>
          </div>

          <form method="POST" class="waitlist-form">
            {% csrf_token %}
            <input type="hidden" name="waitlist" value="1" />
            <button type="submit" class="btn premium">
              {% trans "Join Waitlist" %}
            </button>
          </form>
        </div>
        {% else %}
          {% if user.is_authenticated %}
            <!-- Subscription Form using PlanPurchaseForm -->
            <form method="POST" class="subscription-form" novalidate>
              {% csrf_token %}
              {{ form }}
            </form>
          {% else %}
            <!-- Unauthenticated user content -->
            <div class="subscription-form">
              <div class="signup-prompt">
                <h3>{% trans "You need a MuckRock account to subscribe to this plan." %}</h3>
                <a href="{% url 'account_signup' %}?next={{ request.get_full_path|urlencode }}" class="btn primary">
                  {% trans "Create Account" %}
                </a>
                <p>
                  {% trans "Already have an account?" %}
                  <a class="btn ghost primary" href="{% url 'account_login' %}?next={{ request.get_full_path|urlencode }}">{% trans "Sign in" %}</a>
                </p>
              </div>

              <!-- Price display for unauthenticated users -->
              <div class="form-footer">
                <div class="price">
                  <span class="original-price">${{ plan.base_price|intcomma }}</span>
                  <span class="pay-period">/&nbsp;{% if plan.annual %}{% trans "year" %}{% else %}{% trans "month" %}{% endif %}</span>
                </div>
                <button type="submit" class="btn premium" disabled>
                  {% trans "Subscribe" %}
                </button>
              </div>
            </div>
          {% endif %}
        {% endif %}
        {% if matching_plan %}
          <p class="plan-switch-link">
            <a href="{% url 'plan_detail' pk=matching_plan.pk slug=matching_plan.slug %}">
              {% if plan.annual %}
                {% trans "Also available as a monthly subscription" %}
              {% else %}
                {% trans "Also available as an annual subscription" %}
              {% endif %}
            </a>
          </p>
        {% endif %}
      </div>

      <!-- Plan benefits -->
      {% if plan.benefits %}
      <div class="plan-benefits">
        <h3>{% trans "Plan Benefits" %}</h3>
        <ul class="checklist">
          {% for benefit in plan.benefits %}
          <li class="checklist-item">
            <span class="icon">
              {% include "core/icons/checkmark.svg" %}
            </span>
            <span class="text">{{ benefit }}</span>
          </li>
          {% endfor %}
        </ul>
      </div>
      {% endif %}

      {% if plan.description %}
        <div class="plan-description card">
          {{ plan.description|markdown|safe }}
        </div>
      {% endif %}
    </main>
  </div>
</div>
{% endblock %}

squarelet/templates/payments/plan_enterprise.html
{% extends "account/base.html" %}

{% load i18n static django_vite %}
{% load handleintent pass_query %}
{% load markdown %}

{% block head_title %}{{ plan.name }}{% endblock %}

{% block vite %}
{{ block.super }}
{% vite_asset "frontend/views/select_plan.ts" %}
{% endblock %}

{% block content %}
<div class="container" id="sunlight-enterprise-plan">
  <div class="plan premium">
    <header>
      <h2 class="header-display">
        <span class="heavy-underline premium">{{ plan.name }}</span>
      </h2>
      {% if plan.short_description %}
      <p class="plan-short-description"><strong>{{ plan.short_description }}</strong></p>
      {% endif %}
    </header>

    <main>
      <div class="plan-details card">
        <!-- Plan benefits -->
        {% if plan.benefits %}
        <div class="plan-benefits">
          <ul class="checklist">
            {% for benefit in plan.benefits %}
            <li class="checklist-item">
              <span class="checkmark icon">
                {% include "core/icons/checkmark.svg" %}
              </span>
              <span class="text">{{ benefit }}</span>
            </li>
            {% endfor %}
          </ul>
        </div>
        {% endif %}

        <!-- Contact and Learn More Actions -->
        <div class="plan-actions">
          <a class="button premium" href="https://calendar.app.google/fAWZF635MY89Sp5J9">
            {% trans "Contact us to tailor your plan" %}
          </a>
          <a class="button primary ghost" href="https://sunlightresearch.net/launch" target="_blank">
            {% trans "Learn more" %}
          </a>
        </div>
      </div>

      {% if plan.description %}
        <div class="plan-description card">
          {{ plan.description|markdown|safe }}
        </div>
      {% endif %}
    </main>
  </div>
</div>
{% endblock %}